//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSocialApp.AppResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Polish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Polish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobSocialApp.AppResources.Polish", typeof(Polish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj nowe ogłoszenie.
        /// </summary>
        public static string AddJobButton {
            get {
                return ResourceManager.GetString("AddJobButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaaplikój.
        /// </summary>
        public static string ApplyButtonText {
            get {
                return ResourceManager.GetString("ApplyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz język.
        /// </summary>
        public static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz motyw.
        /// </summary>
        public static string ChooseTheme {
            get {
                return ResourceManager.GetString("ChooseTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj komentarz.
        /// </summary>
        public static string CommentsPlaceholder {
            get {
                return ResourceManager.GetString("CommentsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz nowe miejsca pracy.
        /// </summary>
        public static string CreateNewOpp {
            get {
                return ResourceManager.GetString("CreateNewOpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciemny.
        /// </summary>
        public static string DarkTitle {
            get {
                return ResourceManager.GetString("DarkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        public static string DeleteButtonText {
            get {
                return ResourceManager.GetString("DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj.
        /// </summary>
        public static string EditButtonText {
            get {
                return ResourceManager.GetString("EditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj detale.
        /// </summary>
        public static string EditDetailsMenuItem {
            get {
                return ResourceManager.GetString("EditDetailsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuje ogłoszenie.
        /// </summary>
        public static string EditJob {
            get {
                return ResourceManager.GetString("EditJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj informacje prywatne.
        /// </summary>
        public static string EditPersonalDetails {
            get {
                return ResourceManager.GetString("EditPersonalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj informacje prywatne.
        /// </summary>
        public static string EditProfileTitle {
            get {
                return ResourceManager.GetString("EditProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres e-mail.
        /// </summary>
        public static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angielski.
        /// </summary>
        public static string EnglishTitle {
            get {
                return ResourceManager.GetString("EnglishTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierwsze imię.
        /// </summary>
        public static string FirstNamePlaceholder {
            get {
                return ResourceManager.GetString("FirstNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeMenuItem {
            get {
                return ResourceManager.GetString("HomeMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis stanowiska.
        /// </summary>
        public static string JobDescriptionPlaceHolder {
            get {
                return ResourceManager.GetString("JobDescriptionPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Towje ogłoszenia.
        /// </summary>
        public static string JobsCreatedTitle {
            get {
                return ResourceManager.GetString("JobsCreatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel ogłoszeń.
        /// </summary>
        public static string JobsHubMenuItem {
            get {
                return ResourceManager.GetString("JobsHubMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogłoszenia.
        /// </summary>
        public static string JobsMenuItem {
            get {
                return ResourceManager.GetString("JobsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyszukiwarka pracy.
        /// </summary>
        public static string JobsSearchText {
            get {
                return ResourceManager.GetString("JobsSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł stanowiska.
        /// </summary>
        public static string JobTitlePlaceholder {
            get {
                return ResourceManager.GetString("JobTitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słowo klucz.
        /// </summary>
        public static string KeywordPlaceholder {
            get {
                return ResourceManager.GetString("KeywordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcje językowe.
        /// </summary>
        public static string LanguageOptions {
            get {
                return ResourceManager.GetString("LanguageOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko.
        /// </summary>
        public static string LastNamePlaceholder {
            get {
                return ResourceManager.GetString("LastNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jasny.
        /// </summary>
        public static string LightTitle {
            get {
                return ResourceManager.GetString("LightTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacja.
        /// </summary>
        public static string LocationPlaceHolder {
            get {
                return ResourceManager.GetString("LocationPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masz już konto? Zaloguj się.
        /// </summary>
        public static string LoginAccountInfo {
            get {
                return ResourceManager.GetString("LoginAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę podać adres e-mail oraz hasło aby zalogować się do aplikacji.
        /// </summary>
        public static string LoginInstruction {
            get {
                return ResourceManager.GetString("LoginInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znajdź nową karierę.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string MessagesMenuItem {
            get {
                return ResourceManager.GetString("MessagesMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odległość w milach.
        /// </summary>
        public static string MilesAwayPlaceholder {
            get {
                return ResourceManager.GetString("MilesAwayPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polski.
        /// </summary>
        public static string PolishTitle {
            get {
                return ResourceManager.GetString("PolishTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obecna pozycja.
        /// </summary>
        public static string PositionPlaceholder {
            get {
                return ResourceManager.GetString("PositionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod pocztowy.
        /// </summary>
        public static string PostcodePlaceHolder {
            get {
                return ResourceManager.GetString("PostcodePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij na Facebook&apos;a.
        /// </summary>
        public static string PostToFBPlaceHolder {
            get {
                return ResourceManager.GetString("PostToFBPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ProfileMenuItem {
            get {
                return ResourceManager.GetString("ProfileMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje ogłoszenia.
        /// </summary>
        public static string ProfileTitleLabelCompany {
            get {
                return ResourceManager.GetString("ProfileTitleLabelCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje aplikacje.
        /// </summary>
        public static string ProfileTitleLabelUser {
            get {
                return ResourceManager.GetString("ProfileTitleLabelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternatywnie utwórz nowe konto.
        /// </summary>
        public static string RegisterAccountInfo {
            get {
                return ResourceManager.GetString("RegisterAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestracja.
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpocznij swoją nową karierę.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powtórz hasło.
        /// </summary>
        public static string RePasswordPlaceholder {
            get {
                return ResourceManager.GetString("RePasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wynagrodzenie.
        /// </summary>
        public static string SalaryPlaceHolder {
            get {
                return ResourceManager.GetString("SalaryPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyszukaj.
        /// </summary>
        public static string SearchButtonText {
            get {
                return ResourceManager.GetString("SearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyszukaj ogłoszenia.
        /// </summary>
        public static string SearchJobsTitle {
            get {
                return ResourceManager.GetString("SearchJobsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij.
        /// </summary>
        public static string SendButton {
            get {
                return ResourceManager.GetString("SendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        public static string SettingsMenuItem {
            get {
                return ResourceManager.GetString("SettingsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj.
        /// </summary>
        public static string SignInButton {
            get {
                return ResourceManager.GetString("SignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj.
        /// </summary>
        public static string SignOutMenuItem {
            get {
                return ResourceManager.GetString("SignOutMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij.
        /// </summary>
        public static string SubmitButtonText {
            get {
                return ResourceManager.GetString("SubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcje motywu.
        /// </summary>
        public static string ThemeOptionsTitle {
            get {
                return ResourceManager.GetString("ThemeOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uaktualnij informację.
        /// </summary>
        public static string UpdateDetailsButton {
            get {
                return ResourceManager.GetString("UpdateDetailsButton", resourceCulture);
            }
        }
    }
}
